name: 随机提交(防止Github不活跃被封)
on:
  schedule:
    - cron: '0 2,9,17 * * *'
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    env:
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@v2
        with:
          # PAT申请教程详见：https://www.jianshu.com/p/bb82b3ad1d11,需要repo和workflow权限
          token: ${{ secrets.PAT }} 
      - name: random cron
        if: ${{ env.PAT != ''}}
        run: |
          sed -i -E "s/(- cron: ')[0-9]+( [^[:space:]]+ \* \* \*')/\1$(($RANDOM % 59))\2/g" .github/workflows/deploy.yml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "random cron"
          git push
